# .goreleaser.yaml
version: 2

builds:
  - id: web-app
    main: ./cmd/web-app
    binary: web-app
    ldflags:
      - -s -w -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64