name: Release Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test ./...

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Calculate version
        id: version
        uses: bitshifted/git-auto-semver@v1
        with:
          initial_version: '0.1.0'
          create_tag: true
  
      - name: Set up GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --rm-dist

  deploy:
    runs-on: ubuntu-latest
    needs: release
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4

      - name: Download release binary
        run: |
          curl -L -o web-app.tar.gz https://github.com/kim-groenborg-nielsen/action-demo/releases/latest/download/web-app_linux_amd64.tar.gz
          tar -xzf web-app.tar.gz

      - name: Deploy to production
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > private_key
          chmod 600 private_key
          scp -i private_key web-app $SERVER_USER@$SERVER_HOST:/path/to/deploy/
          ssh -i private_key $SERVER_USER@$SERVER_HOST 'sudo systemctl restart web-app'